# -*- coding: utf-8 -*-
"""Contoh Dasboard Kapal .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHLIQ98KHit4gQcvzUpSbor20-LfzC7G
"""

import pandas as pd
import streamlit as st
import plotly.express as px
from datetime import datetime, timedelta

st.set_page_config(page_title="Monitoring Kapal 6 Jam", layout="wide")

import pandas as pd
import random
from datetime import datetime, timedelta

# Setup
random.seed(42)
kapal_names = ["KM Nusantara", "KM Laut Jaya", "KM Samudra", "KM Pelita", "KM Bintang",
               "KM Armada", "KM Jayabaya", "KM Pelangi", "KM Surya", "KM Baruna"]
jenis_kapal = ["Kapal Penumpang", "Kapal Curah Kering", "Kapal Curah Cair", "Kapal Kontainer"]
terminals = ["Terminal 1", "Terminal 2", "Terminal 3"]

data = []
start_date = datetime(2025, 7, 18, 0, 0)

for _ in range(100):
    nama = random.choice(kapal_names)
    jenis = random.choice(jenis_kapal)
    tanggal = start_date + timedelta(hours=random.randint(0, 120), minutes=random.randint(0, 59))
    durasi = round(random.uniform(2, 12), 1)
    terminal = random.choice(terminals)
    data.append([nama, jenis, tanggal.strftime("%Y-%m-%d %H:%M:%S"), durasi, terminal])

df_dummy = pd.DataFrame(data, columns=[
    "Nama Kapal", "Jenis Kapal", "Tanggal Kedatangan", "Durasi Sandar (jam)", "Terminal"
])
df_dummy.to_csv("dummy_kapal_data_100.csv", index=False)



import streamlit as st

import streamlit as st
import random

import streamlit as st
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - [Nama Perusahaan Anda]</title>
    <style>
        /* Import Font dari Google Fonts */
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');

        /* --- CSS Reset & Global Style --- */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f0f2f5;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            overflow: hidden;
        }

        /* --- Main Container --- */
        .login-container {
            display: flex;
            width: 100%;
            height: 100%;
            max-width: 1200px;
            max-height: 700px;
            background: #fff;
            box-shadow: 0 15px 30px rgba(0,0,0,0.1);
            border-radius: 20px;
            overflow: hidden;
        }

        /* --- Panel Kiri (Visual) --- */
        .left-panel {
            flex: 1;
            background-image: url('https://images.unsplash.com/photo-1577561145218-e794399d5f85?q=80&w=1887&auto=format&fit=crop'); /* <-- GANTI GAMBAR DI SINI */
            background-size: cover;
            background-position: center;
            position: relative;
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            padding: 50px;
            color: #fff;
        }
        
        /* Overlay gelap agar teks terbaca */
        .left-panel::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(to top, rgba(0, 35, 75, 0.8), rgba(0, 35, 75, 0.2));
        }

        .left-panel .welcome-text {
            position: relative; /* Agar di atas overlay */
            z-index: 1;
        }

        .left-panel h1 {
            font-size: 2.5rem;
            line-height: 1.2;
            margin-bottom: 10px;
        }

        .left-panel p {
            font-size: 1rem;
            max-width: 400px;
        }

        /* --- Panel Kanan (Formulir) --- */
        .right-panel {
            flex: 1;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 40px;
        }

        .login-form {
            width: 100%;
            max-width: 380px;
            text-align: center;
        }
        
        .login-form .logo {
            width: 150px;
            margin-bottom: 20px;
        }

        .login-form h2 {
            font-size: 1.8rem;
            color: #333;
            margin-bottom: 10px;
        }

        .login-form .subtitle {
            color: #777;
            margin-bottom: 30px;
        }
        
        /* Styling untuk input field dan floating label */
        .form-group {
            position: relative;
            margin-bottom: 25px;
        }

        .form-input {
            width: 100%;
            padding: 15px;
            border: 1px solid #ccc;
            border-radius: 8px;
            font-size: 1rem;
            background: #f9f9f9;
            transition: border-color 0.3s;
        }

        .form-input:focus {
            outline: none;
            border-color: #0056b3; /* Warna biru korporat */
        }
        
        .form-label {
            position: absolute;
            top: 50%;
            left: 15px;
            transform: translateY(-50%);
            color: #999;
            pointer-events: none;
            transition: all 0.3s ease;
        }

        /* Efek floating label saat input di-fokus atau diisi */
        .form-input:focus + .form-label,
        .form-input:not(:placeholder-shown) + .form-label {
            top: 0px;
            left: 10px;
            font-size: 0.75rem;
            color: #0056b3;
            background: #fff;
            padding: 0 5px;
            transform: translateY(-50%);
        }

        .login-button {
            width: 100%;
            padding: 15px;
            border: none;
            border-radius: 8px;
            background: #0056b3; /* Warna biru korporat */
            color: #fff;
            font-size: 1.1rem;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.3s;
        }

        .login-button:hover {
            background: #003d82; /* Warna biru lebih gelap saat hover */
        }
        
        .forgot-password {
            margin-top: 20px;
            font-size: 0.9rem;
        }

        .forgot-password a {
            color: #0056b3;
            text-decoration: none;
            transition: text-decoration 0.3s;
        }

        .forgot-password a:hover {
            text-decoration: underline;
        }

        /* --- Media Query untuk Tampilan Mobile --- */
        @media (max-width: 800px) {
            .left-panel {
                display: none; /* Sembunyikan panel gambar di mobile */
            }
            .right-panel {
                flex-basis: 100%;
            }
            .login-container {
                border-radius: 0;
                box-shadow: none;
                max-height: 100%;
            }
        }

    </style>
</head>
<body>
    
    <div class="login-container">
        <div class="left-panel">
            <div class="welcome-text">
                <h1>Gerbang Digital Anda</h1>
                <p>Mengintegrasikan layanan logistik dan maritim terdepan untuk efisiensi bisnis Anda.</p>
            </div>
        </div>

        <div class="right-panel">
            <form class="login-form" action="#" method="POST">
                
                <img src="https://pelindo.co.id/themes/pelindo/assets/images/logo/logo-pelindo-white.png" alt="Logo Perusahaan" class="logo" style="filter: invert(25%) sepia(50%) saturate(2500%) hue-rotate(190deg);">

                <h2>Selamat Datang</h2>
                <p class="subtitle">Silakan masuk ke akun Anda</p>
                
                <div class="form-group">
                    <input type="text" id="username" class="form-input" placeholder=" " required>
                    <label for="username" class="form-label">Username</label>
                </div>

                <div class="form-group">
                    <input type="password" id="password" class="form-input" placeholder=" " required>
                    <label for="password" class="form-label">Password</label>
                </div>
                
                <button type="submit" class="login-button">Login</button>

                <div class="forgot-password">
                    <a href="#">Lupa Password?</a>
                </div>

            </form>
        </div>
    </div>

    <script>
        // Sedikit Javascript untuk mencegah form submit (hanya untuk demo)
        const form = document.querySelector('.login-form');
        form.addEventListener('submit', function(event) {
            event.preventDefault(); // Mencegah halaman reload
            
            // Di sini Anda akan menambahkan logika validasi atau pengiriman data ke server
            alert("Tombol Login ditekan! (Aksi default dicegah untuk demo)");

            // Contoh: Mengambil nilai input
            const username = document.getElementById('username').value;
            console.log(`Percobaan login dengan username: ${username}`);
            
            // Setelah login berhasil, arahkan ke halaman dashboard
            // window.location.href = '/dashboard.html';
        });

        // Trik agar floating label bekerja di semua browser, bahkan saat autocomplete
        // dengan memastikan input tidak memiliki placeholder yang terlihat.
        document.querySelectorAll('.form-input').forEach(input => {
            input.setAttribute('placeholder', ' ');
        });
    </script>

</body>
</html>

# --- Halaman Setelah Berhasil Login ---
st.success("✅ Berhasil login! Selamat datang di SmartShip Dashboard.")
st.markdown("📊 Di sini akan muncul dashboard utama...")

# Contoh konten dashboard
st.header("Dashboard Utama")
st.write("Analisis Performa Kapal Anda.")

col1, col2, col3 = st.columns(3)
col1.metric("Total Armada", "12 Kapal", "2")
col2.metric("Efisiensi Bahan Bakar", "85%", "-1.2%")
col3.metric("Kepatuhan Rute", "98%", "0.5%")
# ------------------ DASHBOARD ------------------
st.sidebar.success("Login berhasil!")
st.sidebar.title("Navigasi")
page = st.sidebar.radio("Pilih Halaman:", ["Beranda", "Monitoring", "Statistik", "Tentang"])

if page == "Beranda":
    st.image("https://yourimageurl.com/banner.png", use_column_width=True)
    st.markdown("### 👋 Selamat Datang di Dashboard Monitoring Barang Kapal")
    col1, col2, col3 = st.columns(3)
    col1.metric("Kapal Hari Ini", "17")
    col2.metric("Terminal Aktif", "Terminal 2")
    col3.metric("Update Terakhir", "14:47 WIB")
    
# ---------- BACA DATA ----------
@st.cache_data
def load_data():
    df = pd.read_csv('dummy_kapal_data_100.csv', parse_dates=["Tanggal Kedatangan"])
    return df

df = load_data()

# ---------- FILTER 6 JAM TERAKHIR ----------
now = datetime.now()
six_hours_ago = now - timedelta(hours=6)
df_filtered = df[(df["Tanggal Kedatangan"] >= six_hours_ago) & (df["Tanggal Kedatangan"] <= now)]

st.title("🚢 Dashboard Monitoring Kapal - Update Tiap 6 Jam")
st.subheader(f"Periode: {six_hours_ago.strftime('%H:%M')} - {now.strftime('%H:%M')} WIB, {now.strftime('%d %B %Y')}")
st.markdown(f"⏱️ <b>Update berikutnya:</b> { (now + timedelta(hours=6)).strftime('%H:%M WIB') }", unsafe_allow_html=True)

# ---------- RINGKASAN ----------
col1, col2, col3, col4 = st.columns(4)

# Total Kapal Masuk
col1.metric("Total Kapal Masuk", len(df_filtered))

# Jenis Kapal Terbanyak
if not df_filtered['Jenis Kapal'].mode().empty:
    kapal_terbanyak = df_filtered['Jenis Kapal'].mode().values[0]
else:
    kapal_terbanyak = "Tidak ada data"
col2.metric("Jenis Terbanyak", kapal_terbanyak)

# Rata-rata Durasi Sandar
if not df_filtered.empty:
    rata_sandar = f"{df_filtered['Durasi Sandar (jam)'].mean():.1f} jam"
else:
    rata_sandar = "Tidak ada data"
col3.metric("Rata-rata Sandar", rata_sandar)

# Terminal Paling Aktif
if not df_filtered['Terminal'].mode().empty:
    terminal_aktif = df_filtered['Terminal'].mode().values[0]
else:
    terminal_aktif = "Tidak ada data"
col4.metric("Terminal Paling Aktif", terminal_aktif)

kapal_count = df_filtered['Jenis Kapal'].value_counts().reset_index()
kapal_count.columns = ['Jenis Kapal', 'Jumlah']

fig1 = px.bar(kapal_count,
              x='Jenis Kapal', y='Jumlah',
              labels={'Jenis Kapal': 'Jenis Kapal', 'Jumlah': 'Jumlah Kapal'},
              color='Jenis Kapal',
              text='Jumlah')
st.plotly_chart(fig1, use_container_width=True)

# ---------- GRAFIK JUMLAH PER JAM ----------
st.markdown("### 📈 Jumlah Kapal Masuk per Jam")
df_filtered['jam'] = df_filtered["Tanggal Kedatangan"].dt.strftime('%H:00')
fig2 = px.line(df_filtered.groupby('jam').size().reset_index(name='jumlah'),
               x='jam', y='jumlah', markers=True)
st.plotly_chart(fig2, use_container_width=True)

# Pastikan kolom ada
required_columns = ['timestamp', 'nama_kapal', 'jenis_kapal', 'status', 'terminal', 'durasi_sandar_jam']
missing_columns = [col for col in required_columns if col not in df_filtered.columns]

if missing_columns:
    st.error(f"❌ Kolom berikut tidak ditemukan di DataFrame: {missing_columns}")
else:
    st.markdown("### 📋 Tabel Kedatangan Kapal")
    st.dataframe(df_filtered[required_columns])

# ---------- INSIGHT OTOMATIS ----------
st.markdown("### 💡 Insight Otomatis")
with st.expander("Lihat Insight"):
    st.write(f"- Kapal dengan jenis terbanyak: **{kapal_terbanyak}**")
    st.write(f"- Terminal tersibuk: **{terminal_aktif}**")
    st.write(f"- Rata-rata durasi sandar: **{df_filtered['Durasi Sandar (jam)'].mean():.2f} jam**")
    max_kapal = df_filtered.groupby('jam').size().idxmax()
    st.write(f"- Jam paling sibuk: **{max_kapal}**")

st.markdown("⚠️ Refresh otomatis bisa diatur dengan Streamlit Cloud Scheduler atau crontab di backend.")
