# -*- coding: utf-8 -*-
"""Contoh Dasboard Kapal .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHLIQ98KHit4gQcvzUpSbor20-LfzC7G
"""

import pandas as pd
import streamlit as st
import plotly.express as px
from datetime import datetime, timedelta

st.set_page_config(page_title="Monitoring Kapal 6 Jam", layout="wide")

import pandas as pd
import random
from datetime import datetime, timedelta

# Setup
random.seed(42)
kapal_names = ["KM Nusantara", "KM Laut Jaya", "KM Samudra", "KM Pelita", "KM Bintang",
               "KM Armada", "KM Jayabaya", "KM Pelangi", "KM Surya", "KM Baruna"]
jenis_kapal = ["Kapal Penumpang", "Kapal Curah Kering", "Kapal Curah Cair", "Kapal Kontainer"]
terminals = ["Terminal 1", "Terminal 2", "Terminal 3"]

data = []
start_date = datetime(2025, 7, 18, 0, 0)

for _ in range(100):
    nama = random.choice(kapal_names)
    jenis = random.choice(jenis_kapal)
    tanggal = start_date + timedelta(hours=random.randint(0, 120), minutes=random.randint(0, 59))
    durasi = round(random.uniform(2, 12), 1)
    terminal = random.choice(terminals)
    data.append([nama, jenis, tanggal.strftime("%Y-%m-%d %H:%M:%S"), durasi, terminal])

df_dummy = pd.DataFrame(data, columns=[
    "Nama Kapal", "Jenis Kapal", "Tanggal Kedatangan", "Durasi Sandar (jam)", "Terminal"
])
df_dummy.to_csv("dummy_kapal_data_100.csv", index=False)



import streamlit as st

# ------------------ LOGIN PAGE STYLING ------------------
if 'login' not in st.session_state:
    st.session_state.login = False

if not st.session_state.login:
    # CSS Styling
    st.markdown("""
        <style>
            .login-container {
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100vh;
                background-color: #e6f0ff;
                padding: 20px;
            }
            .login-box {
                background-color: white;
                padding: 40px;
                border-radius: 15px;
                box-shadow: 0px 4px 12px rgba(0,0,0,0.2);
                width: 400px;
            }
            .login-title {
                font-size: 28px;
                font-weight: bold;
                color: #1a75ff;
                margin-bottom: 10px;
                text-align: center;
            }
            .carousel {
                width: 100%;
                height: 180px;
                overflow-x: scroll;
                white-space: nowrap;
            }
            .carousel img {
                height: 160px;
                margin: 0 8px;
                border-radius: 8px;
            }
        </style>
    """, unsafe_allow_html=True)

    # Gambar Carousel
    st.markdown("""
        <div class="carousel">
            <img src="https://images.unsplash.com/photo-1556905055-8f358a7a47b2" />
            <img src="https://i.imgur.com/le5W3tY.jpeg" />
            <img src="https://images.unsplash.com/photo-1618925693387-6ef13eec63f4" />
        </div>
    """, unsafe_allow_html=True)

    # Kotak Login
    st.markdown('<div class="login-container"><div class="login-box">', unsafe_allow_html=True)
    st.markdown('<div class="login-title">📦 Login Dashboard Kapal</div>', unsafe_allow_html=True)

    username = st.text_input("Username")
    password = st.text_input("Password", type="password")

    if st.button("Login"):
        if username == "admin" and password == "123":
            st.session_state.login = True
            st.rerun()
        else:
            st.error("Username atau password salah.")

    st.markdown('</div></div>', unsafe_allow_html=True)
    st.stop()

# ------------------ DASHBOARD ------------------
st.sidebar.success("Login berhasil!")
st.sidebar.title("Navigasi")
page = st.sidebar.radio("Pilih Halaman:", ["Beranda", "Monitoring", "Statistik", "Tentang"])

if page == "Beranda":
    st.image("https://yourimageurl.com/banner.png", use_column_width=True)
    st.markdown("### 👋 Selamat Datang di Dashboard Monitoring Barang Kapal")
    col1, col2, col3 = st.columns(3)
    col1.metric("Kapal Hari Ini", "17")
    col2.metric("Terminal Aktif", "Terminal 2")
    col3.metric("Update Terakhir", "14:47 WIB")
    
# ---------- BACA DATA ----------
@st.cache_data
def load_data():
    df = pd.read_csv('dummy_kapal_data_100.csv', parse_dates=["Tanggal Kedatangan"])
    return df

df = load_data()

# ---------- FILTER 6 JAM TERAKHIR ----------
now = datetime.now()
six_hours_ago = now - timedelta(hours=6)
df_filtered = df[(df["Tanggal Kedatangan"] >= six_hours_ago) & (df["Tanggal Kedatangan"] <= now)]

st.title("🚢 Dashboard Monitoring Kapal - Update Tiap 6 Jam")
st.subheader(f"Periode: {six_hours_ago.strftime('%H:%M')} - {now.strftime('%H:%M')} WIB, {now.strftime('%d %B %Y')}")
st.markdown(f"⏱️ <b>Update berikutnya:</b> { (now + timedelta(hours=6)).strftime('%H:%M WIB') }", unsafe_allow_html=True)

# ---------- RINGKASAN ----------
col1, col2, col3, col4 = st.columns(4)

# Total Kapal Masuk
col1.metric("Total Kapal Masuk", len(df_filtered))

# Jenis Kapal Terbanyak
if not df_filtered['Jenis Kapal'].mode().empty:
    kapal_terbanyak = df_filtered['Jenis Kapal'].mode().values[0]
else:
    kapal_terbanyak = "Tidak ada data"
col2.metric("Jenis Terbanyak", kapal_terbanyak)

# Rata-rata Durasi Sandar
if not df_filtered.empty:
    rata_sandar = f"{df_filtered['Durasi Sandar (jam)'].mean():.1f} jam"
else:
    rata_sandar = "Tidak ada data"
col3.metric("Rata-rata Sandar", rata_sandar)

# Terminal Paling Aktif
if not df_filtered['Terminal'].mode().empty:
    terminal_aktif = df_filtered['Terminal'].mode().values[0]
else:
    terminal_aktif = "Tidak ada data"
col4.metric("Terminal Paling Aktif", terminal_aktif)

kapal_count = df_filtered['Jenis Kapal'].value_counts().reset_index()
kapal_count.columns = ['Jenis Kapal', 'Jumlah']

fig1 = px.bar(kapal_count,
              x='Jenis Kapal', y='Jumlah',
              labels={'Jenis Kapal': 'Jenis Kapal', 'Jumlah': 'Jumlah Kapal'},
              color='Jenis Kapal',
              text='Jumlah')
st.plotly_chart(fig1, use_container_width=True)

# ---------- GRAFIK JUMLAH PER JAM ----------
st.markdown("### 📈 Jumlah Kapal Masuk per Jam")
df_filtered['jam'] = df_filtered["Tanggal Kedatangan"].dt.strftime('%H:00')
fig2 = px.line(df_filtered.groupby('jam').size().reset_index(name='jumlah'),
               x='jam', y='jumlah', markers=True)
st.plotly_chart(fig2, use_container_width=True)

# Pastikan kolom ada
required_columns = ['timestamp', 'nama_kapal', 'jenis_kapal', 'status', 'terminal', 'durasi_sandar_jam']
missing_columns = [col for col in required_columns if col not in df_filtered.columns]

if missing_columns:
    st.error(f"❌ Kolom berikut tidak ditemukan di DataFrame: {missing_columns}")
else:
    st.markdown("### 📋 Tabel Kedatangan Kapal")
    st.dataframe(df_filtered[required_columns])

# ---------- INSIGHT OTOMATIS ----------
st.markdown("### 💡 Insight Otomatis")
with st.expander("Lihat Insight"):
    st.write(f"- Kapal dengan jenis terbanyak: **{kapal_terbanyak}**")
    st.write(f"- Terminal tersibuk: **{terminal_aktif}**")
    st.write(f"- Rata-rata durasi sandar: **{df_filtered['Durasi Sandar (jam)'].mean():.2f} jam**")
    max_kapal = df_filtered.groupby('jam').size().idxmax()
    st.write(f"- Jam paling sibuk: **{max_kapal}**")

st.markdown("⚠️ Refresh otomatis bisa diatur dengan Streamlit Cloud Scheduler atau crontab di backend.")
